build.gradle
src/main/java/devping/nnplanner/NNplannerApplication.java
src/main/java/devping/nnplanner/domain/menu/entity/MonthMenu.java
src/main/java/devping/nnplanner/domain/menucategory/entity/MenuCategory.java
src/main/java/devping/nnplanner/domain/openapi/entity/DailyMenu.java
src/main/java/devping/nnplanner/domain/openapi/entity/Food.java
src/main/java/devping/nnplanner/domain/servey/entity/AdditionalQuestion.java
src/main/java/devping/nnplanner/domain/servey/entity/Servey.java
src/main/java/devping/nnplanner/domain/user/entity/User.java
src/main/java/devping/nnplanner/global/entity/BaseTimeEntity.java
src/main/java/devping/nnplanner/global/entity/HttpStatusResponseEntity.java
src/main/java/devping/nnplanner/global/exception/CustomException.java
src/main/java/devping/nnplanner/global/exception/ErrorCode.java
src/main/java/devping/nnplanner/global/exception/GlobalExceptionHandler.java
src/main/java/devping/nnplanner/global/response/ApiResponse.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application.properties
src/main/resources/application.yml

**1. BaseTimeEntity 구현 했습니다.**
- 생성일자, 생성자/ 수정일자, 수정자가 자동으로 포함되도록 설정 했습니다.
**2. HttpStatusResponseEntity, ApiResponse 구현 했습니다.**
- 자주 사용하는 ResponseEntity<HttpStatus>를 상수로 정의 했습니다.
- `return RESPONSE_OK.body(ApiResponse.of("회원가입 성공", authResponseDTO));`
-  Controller 리턴시 위에 예시대로 리턴 부탁 드립니다.
**3. Exception 설정 했습니다.**
- `BAD_REQUEST(400, "잘못된 요청입니다.")`
- ErrorCode 작성시 위에 예시대로 작성 부탁 드립니다.
- `throw new CustomException(ErrorCode.BAD_REQUEST);`
-  예외 처리시 위에 예시대로 구현 부탁 드립니다.
**4. gradle 세팅 했습니다.**
- Jwt, Webflux, QueryDsl, Spring Rest Docs 의존성 추가 했습니다.
**5. yml 세팅 했습니다.**
- 데이터 베이스 MySQL, MongoDB 설정 했습니다.
- JPA, JWT 설정 했습니다.

feature: grobal 세팅

---

src/main/java/devping/nnplanner/global/entity/HttpStatusResponseEntity.java
src/main/java/devping/nnplanner/global/exception/CustomException.java
src/main/java/devping/nnplanner/global/exception/GlobalExceptionHandler.java

1. 이번에 코드 컨벤션으로 맞춘 구글 자바 스타일을 적용해서 수정했습니다.
- 아래는 코드 설정입니다. 동일하게 맞춰주세요💡

style: 구글 자바 스타일로 코드 스타일 수정

---

build.gradle
src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/domain/auth/dto/response/AuthResponseDTO.java
src/main/java/devping/nnplanner/domain/auth/dto/response/AuthTokenResponseDTO.java
src/main/java/devping/nnplanner/domain/auth/entity/Email.java
src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
src/main/java/devping/nnplanner/global/jwt/token/JwtAuthenticationFilter.java
src/main/java/devping/nnplanner/global/jwt/token/JwtUtil.java
src/main/java/devping/nnplanner/global/jwt/token/RefreshToken.java
src/main/java/devping/nnplanner/global/jwt/token/RefreshTokenRepository.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

1. 로그인시 Access,Refresh Token 을 함께 응답하도록 수정했습니다.
2. 발급된 RefreshToken은 redis에 저장 됩니다.
3. AccessToken 만료시 재발급을 위한 api를 구현 했습니다.
4. 저장된 인증번호 정보를 30분 후 자동으로 삭제 되도록 수정 했습니다.

feature: 리프레시 토큰 구현

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
src/main/java/devping/nnplanner/global/exception/ErrorCode.java
src/main/java/devping/nnplanner/global/jwt/token/BlackList.java
src/main/java/devping/nnplanner/global/jwt/token/BlackListRepository.java
src/main/java/devping/nnplanner/global/jwt/token/JwtUtil.java

1. 로그아웃 api 구현했습니다.
2. blackList를 이용해 accessToken 보안을 강화했습니다.
3. blackList는 redis를 활용했습니다. 유효기간은 3시간입니다.

feature: 로그아웃 api 구현

---

src/main/java/devping/nnplanner/global/config/CorsConfig.java

1. CORS 설정 했습니다.
2. 허용 주소가 여러개일 경우를 대비해 list로 설정해두었습니다.

feature: CORS 설정

---

src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemReader.java
src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemWriter.java
src/main/java/devping/nnplanner/domain/openapi/batch/hospital/HospitalMenuItemProcessor.java
src/main/java/devping/nnplanner/domain/openapi/batch/hospital/HospitalMenuItemReader.java
src/main/java/devping/nnplanner/domain/openapi/batch/hospital/HospitalMenuItemWriter.java
src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
src/main/java/devping/nnplanner/domain/openapi/entity/HospitalMenu.java
src/main/java/devping/nnplanner/domain/openapi/entity/ImportHospitalMenu.java
src/main/java/devping/nnplanner/domain/openapi/repository/FoodRepository.java
src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepository.java
src/main/java/devping/nnplanner/domain/openapi/repository/ImportHospitalMenuRepository.java
src/main/java/devping/nnplanner/global/config/FoodBatchConfig.java
src/main/java/devping/nnplanner/global/config/HospitalBatchConfig.java
src/main/java/devping/nnplanner/global/response/GlobalResponse.java
src/main/resources/application-prod.yml

1. csv 파일을 DB에 import 하기위한 ImportHospitalMenu entity 구현했습니다.
2. import한 병원 식단을 Food 에 매칭하기 위한 필터 기능 구현했습니다.
3. 필터를 수동으로 요청하기 위한 api 구현했습니다.
4. 데이터 처리는 SpringBatch로 구현했습니다.

feature: 병원 식단 필터 api 구현

---

src/main/java/devping/nnplanner/domain/auth/entity/Email.java
src/main/java/devping/nnplanner/domain/auth/entity/User.java
src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
src/main/java/devping/nnplanner/domain/auth/service/EmailService.java

1. setter 사용을 지양하기 위해 builder 사용으로 변경 하였습니다.

fix: setter 삭제

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/domain/auth/dto/request/AuthLoginRequestDTO.java
src/main/java/devping/nnplanner/domain/auth/dto/request/AuthSignRequestDTO.java
src/main/java/devping/nnplanner/domain/auth/dto/request/EmailCodeRequestDTO.java
src/main/java/devping/nnplanner/domain/auth/dto/request/EmailRequestDTO.java
src/main/java/devping/nnplanner/domain/auth/entity/Email.java
src/main/java/devping/nnplanner/domain/auth/entity/User.java
src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
src/main/java/devping/nnplanner/global/jwt/token/JwtAuthenticationFilter.java

1. loginType 을 추가했습니다. LOCAL or GOOGLE
2. bulider 말고 생성자로 create 하도록 재 설정 했습니다.
3. entity에 nullable = false, NotNull 처리를 했습니다.
4. 프론트 와 협의 한대로 size 설정을 했습니다.

fix: auth, email 수정

---

Dockerfile
docker-compose.yml
src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthFoodListResponseDTO.java
src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthMenuPageResponseDTO.java
src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthMenuResponseDTO.java
src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuHospitalRepository.java
src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuRepository.java
src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
src/main/resources/application-prod.yml
src/main/resources/application.yml

1. 식단 전체 조회 api 구현 했습니다.
2. 전체 조회 페이징 처리 구현 했습니다.
3. 식단 상세 조회 api 구현 했습니다. 
-> 상세 조회 부분에 majorCategory 별로 처리하는 로직이 구분 되어야 할 것 같습니다.
이부분은 TODO 로 남겨두었으니 공공데이터 포털에서 학교 데이터가 수정 되면 처리하도록 하겠습니다.

feature: 식단 조회 api 구현

---

src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
src/main/java/devping/nnplanner/domain/monthmenu/entity/MonthMenu.java
src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuHospitalRepository.java
src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java

1. 저장된 식단을 수정할 수 있는 api 구현했습니다.
2. put 으로 수정 되는 방식이지만 식단 부분은 hospitalMenuId 가 null 인경우만 수정 처리됩니다.
3. 중복되는 코드는 메서드로 분리했습니다.

feature: 식단 수정 api 구현

---

src/main/java/devping/nnplanner/domain/auth/entity/Email.java
src/main/java/devping/nnplanner/domain/auth/service/EmailService.java
src/main/java/devping/nnplanner/global/jwt/token/JwtAuthorizationFilter.java

1. 이메일 TTL 부분 수정했습니다.
2. jwt 토큰 문제시 응답메세지 나오도록 수정 했습니다.

fix: 이메일 TTL, 응답 메세지 수정

---

src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java

1. 월별 식단 삭제 api 구현 했습니다.
2. 카테고리가 병원이 아닐 경우는 openAPI 가 정상화 되는대로 추가하도록 하겠습니다.

feature: 월별 식단 삭제 api 구현

---

src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
src/main/java/devping/nnplanner/domain/openapi/repository/FoodRepository.java

1. 음식 정보를 검색할 수 있는 api 구현 했습니다.
2. 검색한 음식과 가장 유사한 정보를 위쪽에 배치하도록 쿼리문을 작성했습니다.
3. 페이징 처리 했습니다.

feature: 음식 정보 검색 api 구현

---

src/main/java/devping/nnplanner/global/config/CorsConfig.java

fix: cors 주소변경

---

src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
src/main/java/devping/nnplanner/domain/user/controller/UserController.java
src/main/java/devping/nnplanner/domain/user/dto/request/UserRequestDTO.java
src/main/java/devping/nnplanner/domain/user/dto/response/UserResponseDTO.java
src/main/java/devping/nnplanner/domain/user/service/UserService.java
src/main/java/devping/nnplanner/global/exception/ErrorCode.java

feature: 비밀번호 확인 api 구현

---

src/main/java/devping/nnplanner/domain/auth/entity/User.java
src/main/java/devping/nnplanner/domain/user/controller/UserController.java
src/main/java/devping/nnplanner/domain/user/dto/request/UserRequestDTO.java
src/main/java/devping/nnplanner/domain/user/service/UserService.java
src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java

1. 비밀번호 수정 api 구현했습니다.
2. request에 패턴 설정이 되어있으니 패턴에 맞게 요청 보내주시길 바랍니다.
`비밀번호는 최소 8자 이상이어야 하며, 소문자와 숫자를 포함해야 합니다.`

feature: 비밀번호 수정 api 구현

---

src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
src/main/java/devping/nnplanner/domain/openapi/dto/response/SchoolInfoResponseDTO.java
src/main/java/devping/nnplanner/domain/openapi/entity/SchoolInfo.java
src/main/java/devping/nnplanner/domain/openapi/service/SchoolInfoService.java

1. webclient 로 학교 정보를 호출해 왔습니다.
2. Async 처리하여 메서드 실행을 비동기 처리 하였습니다.

feature: 학교 기본 정보 호출 api 구현

---

src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java

###주요사항
1. menudate 로만 조회하여 여러 개의 결과가 반환되어 문제가 발생했습니다. 해당 부분을 Id도 함께 조회하여 문제를 없앴습니다.

fix: 월별 메뉴 비즈니스 로직 수정

---

src/main/java/devping/nnplanner/domain/openapi/batch/food/FoodItemReader.java
src/main/java/devping/nnplanner/domain/openapi/batch/schoolMenu/SchoolMenuProcessor.java
src/main/java/devping/nnplanner/domain/openapi/batch/schoolMenu/SchoolMenuReader.java
src/main/java/devping/nnplanner/domain/openapi/batch/schoolMenu/SchoolMenuWriter.java
src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
src/main/java/devping/nnplanner/domain/openapi/dto/response/SchoolMenuApiResponseDTO.java
src/main/java/devping/nnplanner/domain/openapi/dto/response/SchoolMenuDataVO.java
src/main/java/devping/nnplanner/domain/openapi/entity/DailyMenu.java
src/main/java/devping/nnplanner/domain/openapi/entity/SchoolInfo.java
src/main/java/devping/nnplanner/domain/openapi/entity/SchoolMenu.java
src/main/java/devping/nnplanner/domain/openapi/repository/SchoolInfoRepository.java
src/main/java/devping/nnplanner/domain/openapi/repository/SchoolMenuRepository.java
src/main/java/devping/nnplanner/domain/openapi/service/BatchService.java
src/main/java/devping/nnplanner/domain/openapi/service/SchoolInfoService.java
src/main/java/devping/nnplanner/global/config/SchoolBatchConfig.java

1. 학교 정보를 사용해 학교 식단을 호출하는 api 구현했습니다.
2. 배치를 사용해 식단을 호출하도록 구현했습니다.
3. 호출시 비동기적으로 처리되도록 Async 처리 했습니다.
4. 학교 정보 schoolinfo 의 id 값을 Long 타입에서 UUID 로 변경했습니다.

feature: 학교 식단 정보 호출 기능 구현

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
src/main/java/devping/nnplanner/domain/monthmenu/repository/MonthMenuRepository.java
src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java
src/main/java/devping/nnplanner/domain/survey/repository/SurveyRepository.java

1. 회원 탈퇴 api 구현했습니다.
2. 회원 탈퇴시 월별 식단, 식단-병원/ 식단-학교 중간테이블, 설문, 유저 테이블이 삭제 됩니다.
3. 월별 식단 삭제시 설문도 모두 삭제 되도록 로직을 수정하였습니다.

feature: 회원 탈퇴 기능 구현

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
src/main/java/devping/nnplanner/domain/user/controller/UserController.java
src/main/java/devping/nnplanner/domain/user/service/UserService.java

###주요사항
1. user로 설계했던 회원 탈퇴 기능을 auth 로 잘못 구현하여서 api를 이동시켰습니다.

fix: 회원 탈퇴 기능 auth-> user 로 도메인 이동

---

src/main/java/devping/nnplanner/domain/menucategory/service/MenuCategoryService.java
src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
src/main/java/devping/nnplanner/domain/openapi/repository/SchoolInfoRepository.java

1. 카테고리 소분류 조회 학교,학교명 로직 추가 했습니다.
2. 자동 식단 생성시 응답 메세지를 수정했습니다.

fix: 카테고리 소분류 조회 학교,학교명 로직 추가

---

src/main/java/devping/nnplanner/domain/menucategory/entity/MenuCategory.java
src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
src/main/java/devping/nnplanner/domain/openapi/dto/response/RecipeResponseDTO.java
src/main/java/devping/nnplanner/domain/openapi/entity/Recipe.java
src/main/java/devping/nnplanner/domain/openapi/repository/RecipeRepository.java
src/main/java/devping/nnplanner/domain/openapi/service/OpenApiService.java
src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java

###주요기능
1. 월별 레시피 조회 api 구현했습니다.
2. 데이터 길이가 긴 컬럼은 TEXT로 처리하도록 설정했습니다.

feature: 월별 레시피 조회 api 구현

---

src/main/java/devping/nnplanner/domain/menucategory/controller/MenuCategoryController.java
src/main/java/devping/nnplanner/domain/menucategory/entity/MenuCategory.java
src/main/java/devping/nnplanner/domain/menucategory/repository/MenuCategoryRepository.java
src/main/java/devping/nnplanner/domain/menucategory/service/MenuCategoryService.java
src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java

feature: 메뉴 카테고리 import 기능 구현

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/global/exception/ErrorCode.java
src/main/java/devping/nnplanner/global/jwt/token/JwtAuthorizationFilter.java

1. 카멜케이스에서 파스칼케이스로 변경
2. 리프레시 토큰 재발급을 위한 StatusCode 지정
3. 리프레시 토큰 재발급을 위해 body에 StatusCode 응답

fix: 리프레시 토큰 관련 수정

---

src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java

fix: cors 설정 수정

---

src/main/java/devping/nnplanner/global/config/CorsConfig.java
src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java

deploy: 배포

---

src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
src/main/java/devping/nnplanner/domain/monthmenu/dto/response/MonthCountResponseDTO.java
src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java

- requestDTO 로 잘 못 표기 되어있던 파일명을 responseDTO 로  수정했습니다.

fix: 파일명 수정

---

src/main/java/devping/nnplanner/domain/openapi/repository/HospitalMenuRepositoryCustomImpl.java
src/main/java/devping/nnplanner/domain/openapi/repository/SchoolInfoRepository.java

- 병원, 학교명 카테고리 조회시 오름차순으로 나타나도록 수정했습니다.

fix: 병원,학교명 카테고리 오름차순으로 정렬하도록 수정

---

src/main/java/devping/nnplanner/domain/menucategory/controller/MenuCategoryController.java
src/main/java/devping/nnplanner/domain/menucategory/service/MenuCategoryService.java
src/main/java/devping/nnplanner/domain/openapi/repository/SchoolInfoRepository.java
src/main/java/devping/nnplanner/domain/openapi/repository/SchoolInfoRepositoryCustom.java
src/main/java/devping/nnplanner/domain/openapi/repository/SchoolInfoRepositoryImpl.java

- 학교명 검색 api 구현했습니다.
- 글자가 2글자 미만인경우 빈값이 리턴됩니다.
- 오름차순으로 10글자 까지 리턴 됩니다.

feature: 학교명 검색 api 구현

---

src/main/java/devping/nnplanner/domain/user/dto/response/UserResponseDTO.java

del: 필요없는 DTO 제거

---

docker-compose.yml

fix: 환경 변수 추가

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/domain/auth/dto/request/GoogleLoginRequestDTO.java
src/main/java/devping/nnplanner/domain/auth/service/AuthService.java

fix: 구글로그인 프론트로 리디렉션 되도록 수정

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java

fix: Get -> Post 로 매핑 변경

---

src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java

fix: 앤드포인트 변경

---

build.gradle
src/main/java/devping/nnplanner/domain/HomeController.java
src/main/java/devping/nnplanner/domain/auth/controller/AuthController.java
src/main/java/devping/nnplanner/domain/menucategory/controller/MenuCategoryController.java
src/main/java/devping/nnplanner/domain/monthmenu/controller/MonthMenuController.java
src/main/java/devping/nnplanner/domain/openapi/controller/OpenApiController.java
src/main/java/devping/nnplanner/domain/survey/controller/SurveyController.java
src/main/java/devping/nnplanner/domain/user/controller/UserController.java
src/main/java/devping/nnplanner/global/config/SwaggerConfig.java
src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

- Swagger 설정 했습니다.
- 각 컨트롤러 Tag 까지 설정 했습니다. 메소드 Operation은 맡은 도메인에 각자 달아주면 됩니다.
- /swagger-ui 앤드포인트로 접속하면 됩니다.

feature: Swagger 설정

---

src/main/java/devping/nnplanner/domain/auth/service/AuthService.java
src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java

- 구글 로그인시 이미 Local 아이디가 있는 경우 예외 처리
- 식단 자동 생성시 카테고리 요청값이 잘못 될경우 예외 처리

fix: 예외 처리 추가

---

src/main/java/devping/nnplanner/global/config/WebSecurityConfig.java

fix: 앤드 포인트 수정

---

src/main/java/devping/nnplanner/global/config/SwaggerConfig.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

-Mixed Content 문제 해결을 위한 swagger 서버 주소 추가

fix: swagger 서버 주소 추가

---

src/main/java/devping/nnplanner/global/config/SwaggerConfig.java

- swagger 요청시 헤더에 JWT토큰 담아서 요청할수있도록 인증 스키마 추가

fix: swagger 인증 스키마 추가

---

src/main/java/devping/nnplanner/domain/survey/entity/Question.java
src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java

- Question Class 내 Question 수정메서드 캡슐화 목적 작성
- SurveyService 내 추가질문만 수정할 수 있도록 로직 수정
- Survey 질문 수정 로직 변경
- Survey 내 reviseQuestion 메서드 작성

fix : Survey update 로직 수정

---

src/main/java/devping/nnplanner/domain/survey/dto/response/SurveyDetailResponseDTO.java
src/main/java/devping/nnplanner/domain/survey/entity/AnswerItemType.java
src/main/java/devping/nnplanner/domain/survey/entity/SurveyAnswerItem.java
src/main/java/devping/nnplanner/domain/survey/entity/SurveyResponseDetail.java
src/main/java/devping/nnplanner/domain/survey/repository/QuestionRepository.java
src/main/java/devping/nnplanner/domain/survey/repository/ResponseDetailRepository.java
src/main/java/devping/nnplanner/domain/survey/repository/SurveyAnswerItemRepository.java
src/main/java/devping/nnplanner/domain/survey/repository/SurveyRepository.java
src/main/java/devping/nnplanner/domain/survey/repository/SurveyResponseRepository.java
src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java
src/main/java/devping/nnplanner/global/exception/ErrorCode.java

- 날짜로 들어온 내용에 대해서 설문상세 조회시, 가장 많은 날짜에 대해서 3개만 응답값으로 return해주도록 수정 
- SurveyAnswerItem Entity분리
- 기존 SurveyResponseDetail Entity에서 List<String>으로 갖고있던 값을 Service Layer에서 분기처리위해 Entity로 따로 분리

Feat : Survey 상세 조회 기능 수정 및 SurveyAnswerItem Entity 추가

---

src/main/java/devping/nnplanner/domain/monthmenu/service/MonthMenuService.java

- 중복된 분기 로직을 switch 문으로 통합하여 가독성과 유지보수성을 향상시켰습니다.
- 메뉴 유형별 중복된 코드 구조를 간결하게 리팩터링했습니다.

refactor: 중복 코드 리팩터링, if -> switch 리팩터링

---

src/main/java/devping/nnplanner/domain/menucategory/service/MenuCategoryService.java

fix: 트랜잭션 추가

---

src/main/java/devping/nnplanner/domain/survey/service/SurveyService.java

- questionId가 Null일 경우, 새로운 질문추가로 판단하여 DB에 저장 후 값 Return하도록 수정

feat : 설문 수정시, 새로운 질문 추가 기능 구현
